<?php

    $fileType = 'xlsx'; //in file format
    $startAtRow = 2; //min 1, allow skipping headers rows
    
    //specific
    $priceMultiplier = 1;
    
    //configurable
    $hasConfigurable = true;
    $configurablePrice = 'lowest_simple';
    $configurableSpecialPrice = 'lowest_simple';
    $configurableWeight = 'lowest_simple';
    $configurableGroup = '{A}';
    
    //override row value for configurable
    $configurableRow['type'] = 'configurable';
    $configurableRow['configurable_attributes'] = 'rug_size';
    $configurableRow['_super_attribute_code'] = 'rug_size';
    $configurableRow['sku'] = 'RIZZY-{A}';
    $configurableRow['associated'] = 'RIZZY-{A}';
    $configurableRow['name'] = 'Rizzy {F} Rug in {P}';
    $configurableRow['product_name'] = 'Rizzy {F} Rug in {P}';
    $configurableRow['qty'] = '1';
    $configurableRow['visibility'] = '4';
    $configurableRow['meta_title'] = 'Rizzy {F} Rug in {P}';
    $configurableRow['has_options'] = '1';
    $configurableRow['product_type_id'] = 'configurable';	
    
    //matching IN -> OUT format
    $row['store'] = 'admin';
    $row['store_id'] = '0';
    $row['websites'] = 'Base';
    $row['attribute_set'] = 'Rugs';
    $row['type'] = 'simple';
    $row['configurable_attributes'] = '';
    $row['_super_attribute_code'] = '';
    $row['category_ids'] = '83,6';
    $row['sku'] = 'RIZZY-{A}-{G}';
    $row['associated'] = '';
    $row['name'] = 'Rizzy {F} Rug in {P}-{G}';
    $row['manufacturer'] = 'Rizzy';
    $row['mfg_model'] = '{D}';
    $row['aw_callforprice'] = '';
    $row['msrp_enabled'] = 'Use config';
    $row['msrp_display_actual_price_type'] = 'Use config';
    $row['msrp'] = '';
    $row['price'] = '{I}';
    $row['special_price'] = '{J}';
    $row['special_from_date'] = '';
    $row['special_to_date'] = '';
    $row['weight'] = '{P}';
    $row['tax_class_id'] = '2';
    $row['qty'] = 'TODO';
    $row['min_qty'] = '0';
    $row['use_config_min_qty'] = '1';
    $row['is_qty_decimal'] = '0';
    $row['backorders'] = '0';
    $row['use_config_backorders'] = '1';
    $row['min_sale_qty'] = '1';
    $row['use_config_min_sale_qty'] = '1';
    $row['max_sale_qty'] = '0';
    $row['use_config_max_sale_qty'] = '1';
    $row['is_in_stock'] = '1';
    $row['low_stock_date'] = '';
    $row['notify_stock_qty'] = '0';
    $row['use_config_notify_stock_qty'] = '1';
    $row['manage_stock'] = '0';
    $row['use_config_manage_stock'] = '1';
    $row['stock_status_changed_auto'] = '0';
    $row['use_config_qty_increments'] = '1';
    $row['qty_increments'] = '0';
    $row['use_config_enable_qty_inc'] = '1';
    $row['enable_qty_increments'] = '0';
    $row['is_decimal_divided'] = '0';
    $row['stock_status_changed_automatically'] = '0';
    $row['use_config_enable_qty_increments'] = '1';
    $row['status'] = '1';
    $row['visibility'] = '1';
    $row['is_recurring'] = 'No';
    $row['url_key'] = '';
    $row['url_path'] = '';
    $row['meta_title'] = 'Rizzy {F} Rug in {P}-{G}';
    $row['meta_description'] = '';
    $row['meta_keyword'] = '';
    $row['image_label'] = '';
    $row['small_image_label'] = '';
    $row['thumbnail_label'] = '';
    $row['image'] = '/rizzy/{A}.jpg';
    $row['small_image'] = '/rizzy/{A}.jpg';
    $row['thumbnail'] = '/rizzy/{A}.jpg';
    $row['media_gallery'] = '';
    $row['description'] = '{K}';
    $row['short_description'] = '';
    $row['feature_1'] = '';
    $row['feature_2'] = '';
    $row['feature_3'] = '';
    $row['feature_4'] = '';
    $row['rug_color'] = array(
        'VALUE' => '{P}',
        'Aqua ' => 'Blues',
        'Ash' => 'Grays',
        'Aubergine ' => 'Reds',
        'Baby Blue ' => 'Blues',
        'Beige ' => 'Browns/Beiges',
        'BEIGE/BEIGE' => 'Browns/Beiges',
        'BEIGE/BLUE ' => 'Browns/Beiges',
        'BEIGE/BROWN ' => 'Browns/Beiges',
        'BEIGE/GOLD' => 'Browns/Beiges',
        'Beige / Light Blue' => 'Browns/Beiges',
        'Beige / Light Brown' => 'Browns/Beiges',
        'Beige / Multi' => 'Browns/Beiges',
        'Beige/Black' => 'Browns/Beiges',
        'BEIGE/GRAY' => 'Browns/Beiges',
        'BEIGE/GREEN' => 'Browns/Beiges',
        'BEIGE/LIGHT GRAY' => 'Browns/Beiges',
        'BEIGE/RED' => 'Browns/Beiges',
        'BEIGE/RUST ' => 'Browns/Beiges',
        'Black ' => 'Blacks',
        'Black / Beige' => 'Blacks',
        'BLACK/GRAY ' => 'Blacks',
        'Blanc ' => 'Neutrals',
        'Blue ' => 'Blues',
        'Blue / Beige' => 'Blues',
        'BLUE/IVORY' => 'Blues',
        'BLUE/RUST ' => 'Blues',
        'Brown ' => 'Browns/Beiges',
        'BROWN/BEIGE ' => 'Browns/Beiges',
        'Brown / Blue' => 'Browns/Beiges',
        'Brown / Burgundy' => 'Browns/Beiges',
        'Brown / Charcoal' => 'Browns/Beiges',
        'BROWN/GREEN ' => 'Browns/Beiges',
        'BROWN/IVORY' => 'Browns/Beiges',
        'BROWN/RED ' => 'Browns/Beiges',
        'BROWN/TAN ' => 'Browns/Beiges',
        'Burn ' => 'Reds',
        'Burgandy ' => 'Reds',
        'Burgundy / Green' => 'Reds',
        'Burgundy ' => 'Reds',
        'BURGUNDY/BLACK' => 'Reds',
        'Camel ' => 'Neutrals',
        'Charcoal ' => 'Grays',
        'Charcoal / Beige' => 'Grays',
        'Charcoal/Brown' => 'Browns/Beiges',
        'Chocolate ' => 'Browns/Beiges',
        'Coal / Gold' => 'Grays',
        'Coral' => 'Reds',
        'Cream ' => 'Neutrals',
        'CREAM/GRAY ' => 'Neutrals',
        'D. Blue' => 'Blues',
        'Dark Brown' => 'Browns/Beiges',
        'Dark Grey' => 'Grays',
        'Dawn' => 'Multi',
        'Dusk' => 'Neutrals',
        'Emerald Green' => 'Greens',
        'Espresso' => 'Browns/Beiges',
        'Fuschia' => 'Purples',
        'Dark Gold ' => 'Yellows/Golds',
        'Darkbrown' => 'Browns/Beiges',
        'GOLD ' => 'Yellows/Golds',
        'GOLD/RED ' => 'Yellows/Golds',
        'Gray' => 'Grays',
        'Gray / Beige' => 'Grays',
        'GRAY/BLUE' => 'Grays',
        'Gray / Gold' => 'Grays',
        'Gray / Ivory' => 'Grays',
        'Gray / Multi' => 'Grays',
        'Gray / Pink' => 'Grays',
        'Gray / Rust' => 'Grays',
        'Gray / Yellow' => 'Grays',
        'Gray/Gold' => 'Grays',
        'GREEN' => 'Greens',
        'Green / Olive' => 'Greens',
        'Grey' => 'Grays',
        'GRAY/ORANGE' => 'Grays',
        'Gunmetal ' => 'Grays',
        'Hemlo / Green' => 'Greens',
        'Hopi Red ' => 'Reds',
        'Hot Pink' => 'Pinks',
        'Indigo Blue ' => 'Blues',
        'Ivory ' => 'Neutrals',
        'Ivory / Brown ' => 'Browns/Beiges',
        'IVORY/BLUE' => 'Neutrals',
        'Ivory / Charcoal' => 'Neutrals',
        'Ivory / Gold' => 'Neutrals',
        'Ivory / Gray' => 'Neutrals',
        'Ivory / Green' => 'Neutrals',
        'Ivory / Pink' => 'Neutrals',
        'Ivory / Plum' => 'Neutrals',
        'Ivory / Red' => 'Neutrals',
        'IVORY/RUST' => 'Neutrals',
        'IVORY/TAN ' => 'Neutrals',
        'Latte ' => 'Browns/Beiges',
        'Light / Blue' => 'Blues',
        'Light / Grey' => 'Grays',
        'Light Beige ' => 'Neutrals',
        'Light Blue ' => 'Blues',
        'LIGHT BLUE/BEIGE ' => 'Blues',
        'LIGHT BROWN' => 'Browns/Beiges',
        'LIGHT BROWN/IVORY ' => 'Browns/Beiges',
        'Light Gold ' => 'Yellows/Golds',
        'LIGHT GOLD/BROWN ' => 'Yellows/Golds',
        'Light Gray ' => 'Grays',
        'Light Green ' => 'Greens',
        'Light Orange' => 'Oranges/Rust',
        'Lightgold ' => 'Yellows/Golds',
        'Lime ' => 'Greens',
        'Lime / White' => 'Greens',
        'Lime White' => 'Greens',
        'Lipstick Red ' => 'Reds',
        'Lux' => 'Browns/Beiges',
        'Mauve' => 'Pinks',
        'LITE GOLD/LITE GOLD ' => 'Yellows/Golds',
        'MEDIUM BLUE ' => 'Blues',
        'Mocha ' => 'Browns/Beiges',
        'MULTI ' => 'Multi',
        'MULTI/MULTI ' => 'Multi',
        'Mykonos Blue' => 'Blues',
        'Natural ' => 'Neutrals',
        'Navajo Red ' => 'Reds',
        'Navy' => 'Blues',
        'NAVY/GOLD ' => 'Blues',
        'Navy / Plum' => 'Blues',
        'NAVY/IVORY ' => 'Blues',
        'NAVY/RED ' => 'Blues',
        'Off White' => 'Neutrals',
        'Olive ' => 'Greens',
        'ORANGE ' => 'Oranges/Rust',
        'Pewter' => 'Grays',
        'Pink ' => 'Pinks',
        'PLUM ' => 'Purples',
        'Purple' => 'Purples',
        'Purple / Multi' => 'Purples',
        'Pumpkin ' => 'Oranges/Rust',
        'RED ' => 'Reds',
        'RED/BEIGE ' => 'Reds',
        'RED/BLUE ' => 'Reds',
        'Red / Gold' => 'Reds',
        'RED/GREEN ' => 'Reds',
        'RED/IVORY' => 'Reds',
        'Redoxide' => 'Reds',
        'Rust ' => 'Oranges/Rust',
        'Rust / Ivory' => 'Oranges/Rust',
        'Rust / Light Brown' => 'Oranges/Rust',
        'RUST/BEIGE ' => 'Oranges/Rust',
        'Sage ' => 'Greens',
        'Scarlet' => 'Reds',
        'Sea Blue' => 'Blues',
        'Shell More' => 'Browns/Beiges',
        'SILVER ' => 'Grays',
        'Skyblue' => 'Blues',
        'Slate ' => 'Grays',
        'Slate / Gold' => 'Grays',
        'Slate Blue ' => 'Blues',
        'Stone' => 'Grays',
        'Solid Gold ' => 'Yellows/Golds',
        'Solid Red ' => 'Reds',
        'Solid Sage ' => 'Greens',
        'Solid White ' => 'Neutrals',
        'Spice ' => 'Oranges/Rust',
        'Sunflower' => 'Yellows/Golds',
        'Tan ' => 'Browns/Beiges',
        'Teal ' => 'Blues',
        'Teal / Turquoise' => 'Blues',
        'Teal Lime' => 'Blues',
        'Teal/Blue' => 'Blues',
        'Terracotta ' => 'Oranges/Rust',
        'Turquoise' => 'Blues',
        'WHITE ' => 'Neutrals',
        'WHITE/GRAY ' => 'Neutrals',
        'Yellow ' => 'Yellows/Golds',
        'Yellow / White' => 'Yellows/Golds',
    );
    
    $row['rug_shape'] = array(
        'VALUE' => '{G}',
        '10\' x 14\'' => 'Rectangle',
        '1\'8" x 2\'6"' => 'Rectangle',
        '2\' x 3\'' => 'Rectangle',
        '2\' x 3\'7"' => 'Rectangle',
        '2\'3" x 7\'7"' => 'Rectangle',
        '2\'6" x 10\'' => 'Hall/Stair Runner',
        '2\'6" x 4\'' => 'Rectangle',
        '2\'6" x 6\'' => 'Rectangle',
        '2\'6" x 8\'' => 'Hall/Stair Runner',
        '3\' x 3\' Round' => 'Round',
        '3\' x 5\'' => 'Rectangle',
        '3\'3" x 5\'3"' => 'Rectangle',
        '3\'6" x 5\'6"' => 'Rectangle',
        '4\' x 5\'7"' => 'Rectangle ',
        '4\' x 6\'' => 'Rectangle',
        '5\' x 7\'' => 'Rectangle',
        '5\' x 8\'' => 'Rectangle',
        '5\'3" x 7\'7"' => 'Rectangle',
        '5\'6" x 8\'6"' => 'Rectangle',
        '6\' x 9\'' => 'Rectangle',
        '6\'7" x 9\'6"' => 'Rectangle',
        '7\'10" x 10\'10"' => 'Rectangle',
        '8\' x 10\'' => 'Rectangle',
        '8\' x 8\' Round' => 'Round',
        '8\' x 8\' Square' => 'Square',
        '9\' x 12\'' => 'Rectangle',
        '9\'2" x 12\'6"' => 'Rectangle',
    );



    $row['rug_style'] = array(
        'VALUE' => '{Q}',
        'Animal Print ' => 'Animal Prints/Hides',
        'Contemporary  ' => 'Contemporary/Modern',
        'Damask ' => 'Traditional',
        'Floral ' => 'Floral',
        'Foliage ' => 'Floral',
        'Geometric ' => 'Geometric',
        'Lattice ' => 'Geometric',
        'Lodge ' => 'Southwest/Lodge',
        'Medallion ' => 'Transitional',
        'Modern ' => 'Contemporary/Modern',
        'Paisley ' => 'Floral',
        'Shag ' => 'Shag',
        'Solid ' => 'Solid',
        'Southwest ' => 'Southwest/Lodge',
        'Stripes ' => 'Stripes',
        'Traditional ' => 'Traditional',
        'Transitional ' => 'Transitional',
        'Tribal ' => 'Southwest/Lodge',
    );

    $row['rug_nav'] = array(
        'VALUE' => '{G}',
        '10\' x 14\'' => '10\' x 14\'',
        '1\'8" x 2\'6"' => '2\' x 3\'',
        '2\' x 3\'' => '2\' x 3\'',
        '2\' x 3\'7"' => '2\' x 4\'',
        '2\'3" x 7\'7"' => 'Runners 6\'-9\'',
        '2\'6" x 10\'' => 'Runners 10\'-11\'',
        '2\'6" x 4\'' => '3\' x 4\'',
        '2\'6" x 6\'' => '2\' x 6\'',
        '2\'6" x 8\'' => 'Runners 8\'-9\'',
        '3\' x 3\' Round' => 'Round-Small',
        '3\' x 5\'' => '3\' x 5\'',
        '3\'3" x 5\'3"' => '3\' x 5\'',
        '3\'6" x 5\'6"' => '3\'6" x 5\'6"',
        '4\' x 5\'7"' => '4\' x 6\'',
        '4\' x 6\'' => '4\' x 6\'',
        '5\' x 7\'' => '5\' x 7\'',
        '5\' x 8\'' => '5\' x 8\'',
        '5\'3" x 7\'7"' => '5\'6" x 7\'6"',
        '5\'6" x 8\'6"' => '6\' x 9\'',
        '6\' x 9\'' => '6\' x 9\'',
        '6\'7" x 9\'6"' => '7\' x 9\'',
        '7\'10" x 10\'10"' => '8\' x 11\'',
        '7\'10" x 7\'10" Round' => 'Round 7\'-8\'',
        '8\' x 10\'' => '8\' x 10\'',
        '8\' x 8\' Round' => 'Round 7\'-8\'',
        '8\' x 8\' Square' => 'Square 7\'-8\'',
        '9\' x 12\'' => '9\' x 12\'',
        '9\'10" x 12\'6"' => '9\' x 12\'',
        '9\'2" x 12\'6"' => '9\' x 12\'',
    );


    $row['rug_size'] = array(
        'VALUE' => '{G}',
        '10\' x 14\'' => '10\' x 14\'',
        '1\'8" x 2\'6"' => '1\'8" x 2\'6"',
        '2\' x 3\'' => '2\' x 3\'',
        '2\' x 3\'7"' => '2\' x 3\'7"',
        '2\'3" x 7\'7"' => '2\'3" x 7\'7" Runner',
        '2\'6" x 10\'' => '2\'6" x 10\' Runner',
        '2\'6" x 4\'' => '2\'6" x 4\'',
        '2\'6" x 6\'' => '2\'6" x 6\'',
        '2\'6" x 8\'' => '2\'6" x 8\' Runner',
        '3\' x 3\' Round' => '3\' x 3\' Round',
        '3\' x 5\'' => '3\' x 5\'',
        '3\'3" x 5\'3"' => '3\'3" x 5\'3"',
        '3\'6" x 5\'6"' => '3\'6" x 5\'6"',
        '4\' x 5\'7"' => '4\' x 5\'7"',
        '4\' x 6\'' => '4\' x 6\'',
        '5\' x 7\'' => '5\' x 7\'',
        '5\' x 8\'' => '5\' x 8\'',
        '5\'3" x 7\'7"' => '5\'3" x 7\'7"',
        '5\'6" x 8\'6"' => '5\'6" x 8\'6"',
        '6\' x 9\'' => '6\' x 9\'',
        '6\'7" x 9\'6"' => '6\'7" x 9\'6"',
        '7\'10" x 10\'10"' => '7\'10" x 10\'10"',
        '7\'10" x 7\'10" Round' => '7\'10" x 7\'10" Round',
        '8\' x 10\'' => '8\' x 10\'',
        '8\' x 8\' Round' => '8\' x 8\' Round',
        '8\' x 8\' Square' => '8\' x 8\' Square',
        '9\' x 12\'' => '9\' x 12\'',
        '9\'10" x 12\'6"' => '9\'10" x 12\'6"',
        '9\'2" x 12\'6"' => '9\'2" x 12\'6"',
     );

    $row['rug_material'] = '{L}';
    $row['mfg_collection'] = '';
    $row['assembly_req'] = '';
    $row['country_of_manufacture'] = '';
    $row['ship_type'] = 'Drop Ship';
    $row['lead_time'] = '14 Days';
    $row['enable_googlecheckout'] = 'Yes';
    $row['gift_message_available'] = 'No';
    $row['has_options'] = '0';
    $row['custom_layout_update'] = '';
    $row['page_layout'] = '1 column';
    $row['options_container'] = 'container1';
    $row['custom_design'] = '';
    $row['custom_design_from'] = '';
    $row['custom_design_to'] = '';
    $row['news_from_date'] = '';
    $row['news_to_date'] = '';
    $row['reward_no_discount'] = '';
    $row['reward_points'] = '';
    $row['product_name'] = 'Rizzy {F} Rug in {P}-{G}';
    $row['product_type_id'] = 'simple';
    $row['product_status_changed'] = '';
    $row['product_changed_websites'] = '';
    $row['recurring_profile'] = '';
    $row['shipping_height'] = '{W}';
    $row['shipping_width'] = '{V}';
    $row['shipping_length'] = '{U}';
    $row['pile_height'] = '{N}-Pile Height';
    $row['construction'] = 'Hand Knotted';
    $row['stain_resistant'] = '';
    $row['fire_resistant'] = '';
    $row['care_cleaning'] = '{S}';
    $row['warranty'] = '';
    $row['upc'] = '{E}';

    