<?php

    $fileType = 'xlsx'; //in file format
    $startAtRow = 2; //min 1, allow skipping headers rows
    
    //specific
    $priceMultiplier = 1.5;
    
    //configurable
    $hasConfigurable = true;
    $configurablePrice = 'lowest_simple';
    $configurableSpecialPrice = 'lowest_simple';
    $configurableWeight = 'lowest_simple';
    $configurableGroup = '{D}{E}';
    
    //override row value for configurable
    $configurableRow['type'] = 'configurable';
    $configurableRow['configurable_attributes'] = 'rug_size';
    $configurableRow['_super_attribute_code'] = 'rug_size';
    $configurableRow['sku'] = 'FEIZY-{D}-{E}';
    $configurableRow['associated'] = 'FEIZY-{D}-{E}';
    $configurableRow['name'] = 'Feizy {C} Rug in {F}';
    $configurableRow['qty'] = '1';
    $configurableRow['visibility'] = '4';
    $configurableRow['meta_title'] = 'Feizy {C} Rug in {F}';
    $configurableRow['has_options'] = '1';
    $configurableRow['product_type_id'] = 'configurable';	
    
    //matching IN -> OUT format
    $row['store'] = 'admin';
    $row['store_id'] = '0';
    $row['websites'] = 'Base';
    $row['attribute_set'] = 'Rugs';
    $row['type'] = 'simple';
    $row['configurable_attributes'] = '';
    $row['_super_attribute_code'] = '';
    $row['category_ids'] = '90,6';
    $row['sku'] = 'FEIZY-{D}-{E}-{H}';
    $row['associated'] = '';
    $row['name'] = 'Feizy {C} Rug in {F}-{H}';
    $row['manufacturer'] = 'Feizy';
    $row['mfg_model'] = '{I}';
    $row['aw_callforprice'] = '';
    $row['msrp_enabled'] = 'Use config';
    $row['msrp_display_actual_price_type'] = 'Use config';
    $row['msrp'] = '';
    $row['price'] = '{W}';
    $row['special_price'] = '{W}';
    $row['special_from_date'] = '';
    $row['special_to_date'] = '';
    $row['weight'] = '{P}';
    $row['tax_class_id'] = '2';
    $row['qty'] = 'TODO';
    $row['min_qty'] = '0';
    $row['use_config_min_qty'] = '1';
    $row['is_qty_decimal'] = '0';
    $row['backorders'] = '0';
    $row['use_config_backorders'] = '1';
    $row['min_sale_qty'] = '1';
    $row['use_config_min_sale_qty'] = '1';
    $row['max_sale_qty'] = '0';
    $row['use_config_max_sale_qty'] = '1';
    $row['is_in_stock'] = '1';
    $row['low_stock_date'] = '';
    $row['notify_stock_qty'] = '0';
    $row['use_config_notify_stock_qty'] = '1';
    $row['manage_stock'] = '0';
    $row['use_config_manage_stock'] = '1';
    $row['stock_status_changed_auto'] = '0';
    $row['use_config_qty_increments'] = '1';
    $row['qty_increments'] = '0';
    $row['use_config_enable_qty_inc'] = '1';
    $row['enable_qty_increments'] = '0';
    $row['is_decimal_divided'] = '0';
    $row['stock_status_changed_automatically'] = '0';
    $row['use_config_enable_qty_increments'] = '1';
    $row['status'] = '1';
    $row['visibility'] = '1';
    $row['is_recurring'] = 'No';
    $row['url_key'] = '';
    $row['url_path'] = '';
    $row['meta_title'] = 'Feizy {C} Rug in {F}-{H}';
    $row['meta_description'] = '';
    $row['meta_keyword'] = '';
    $row['image_label'] = '';
    $row['small_image_label'] = '';
    $row['thumbnail_label'] = '';
    $row['image'] = '/feizy/{Y}.jpg';
    $row['small_image'] = '/feizy/{Y}.jpg';
    $row['thumbnail'] = '/feizy/{Y}.jpg';
    $row['media_gallery'] = '';
    $row['description'] = '{X}';
    $row['short_description'] = '';
    $row['feature_1'] = '';
    $row['feature_2'] = '';
    $row['feature_3'] = '';
    $row['feature_4'] = '';
    $row['rug_color'] = array(
        'VALUE' => '{F}',
        'Almond' => 'Neutrals',
        'Amber' => 'Multi',
        'Apricot' => 'Reds',
        'Aqua' => 'Neutrals',
        'Ash' => 'Neutrals',
        'Asphalt' => 'Grays',
        'Assorted' => 'Multi',
        'Atlantic' => 'Blues',
        'Aura' => 'Blues',
        'Avocado' => 'Greens',
        'Azure' => 'Multi',
        'Beige' => 'Browns/Beiges',
        'Beige/Beige' => 'Browns/Beiges',
        'Beige/Brown' => 'Browns/Beiges',
        'Beige/Rust' => 'Browns/Beiges',
        'Black' => 'Blacks',
        'Black / Dark Gray' => 'Blacks',
        'Black / Ecru' => 'Blacks',
        'Black / Silver' => 'Blacks',
        'Black / White' => 'Blacks',
        'Black / Zinc' => 'Blacks',
        'Black/Beige' => 'Browns/Beiges',
        'Black/Black' => 'Browns/Beiges',
        'Black/Charcoal' => 'Blacks',
        'Black/Gold' => 'Multi',
        'Black/Multi' => 'Blacks',
        'Black/Navy' => 'Blues',
        'Black/Red' => 'Multi',
        'Blue' => 'Blues',
        'Blue/Multi' => 'Multi',
        'Blush' => 'Multi',
        'Bonsai' => 'Greens',
        'Brown' => 'Browns/Beiges',
        'Brown / Light Brown' => 'Browns/Beiges',
        'Brown/Beige' => 'Browns/Beiges',
        'Brown/Brown' => 'Browns/Beiges',
        'Burlap' => 'Browns/Beiges',
        'Camel' => 'Browns/Beiges',
        'Camel/Black' => 'Multi',
        'Caramel' => 'Browns/Beiges',
        'Carpri' => 'Multi',
        'Cashmere' => 'Neutrals',
        'Celadon' => 'Blues',
        'Celery/Ivory' => 'Browns/Beiges',
        'Cerulean' => 'Blues',
        'Charcoal' => 'Blacks',
        'Cherry' => 'Reds',
        'Chocolate' => 'Browns/Beiges',
        'Chocolate / Red' => 'Reds',
        'Chocolate/Ivory' => 'Browns/Beiges',
        'Cinnamon/Plum' => 'Oranges/Rust',
        'Citron' => 'Neutrals',
        'Coal' => 'Grays',
        'Cobalt' => 'Blues',
        'Cobalt / White' => 'Blues',
        'Coffee / Gray' => 'Browns/Beiges',
        'Coffee / Rust' => 'Oranges/Rust',
        'Concord' => 'Multi',
        'Copper' => 'Multi',
        'Cordovan' => 'Pinks',
        'Cornflower' => 'Blues',
        'Cranberry' => 'Reds',
        'Cranberry/Ivory' => 'Browns/Beiges',
        'Cream' => 'Neutrals',
        'Cream / Aqua' => 'Multi',
        'Cream / Brown' => 'Neutrals',
        'Cream / Dark Gray' => 'Blues',
        'Cream / Ecru' => 'Neutrals',
        'Cream / Light Silver' => 'Neutrals',
        'Cream / Marine' => 'Blues',
        'Cream / Nutmeg' => 'Multi',
        'Cream / Sage' => 'Yellows/Golds',
        'Cream / Silver' => 'Grays',
        'Cream / Spa Blue' => 'Yellows/Golds',
        'Cream/Charcoal' => 'Multi',
        'Cream/Cream' => 'Neutrals',
        'Cream/Gray' => 'Neutrals',
        'Cream/Multi' => 'Multi',
        'Cream/Navy' => 'Neutrals',
        'Cream/Red' => 'Reds',
        'Crimson' => 'Reds',
        'Crimson/Multi' => 'Multi',
        'Dark Blue' => 'Blues',
        'Dark Blue / Gray' => 'Neutrals',
        'Dark Brown' => 'Browns/Beiges',
        'Dark Brown/Green' => 'Browns/Beiges',
        'Dark Chocolate' => 'Browns/Beiges',
        'Dark Chocolate / Aqua' => 'Multi',
        'Dark Chocolate / Ecru' => 'Multi',
        'Dark Chocolate / Gray' => 'Browns/Beiges',
        'Dark Chocolate / Multi' => 'Browns/Beiges',
        'Dark Chocolate / Rust' => 'Multi',
        'Dark Chocolate / Sage' => 'Browns/Beiges',
        'Dark Chocolate / Silver' => 'Grays',
        'Dark Gray' => 'Grays',
        'Dark Gray / Dark Gray' => 'Grays',
        'Dark Gray / Green' => 'Browns/Beiges',
        'Dark Gray / Marine' => 'Blues',
        'Dark Gray / Raspberry' => 'Pinks',
        'Dark Gray / Silver' => 'Grays',
        'Denim' => 'Neutrals',
        'Driftwood' => 'Neutrals',
        'Dusk' => 'Multi',
        'Ebony / White' => 'Blacks',
        'Elderberry' => 'Reds',
        'Flame' => 'Multi',
        'Flamingo' => 'Multi',
        'Fog' => 'Grays',
        'Fountain' => 'Multi',
        'Fuschia' => 'Reds',
        'Galaxy' => 'Multi',
        'Geranium' => 'Multi',
        'Gold' => 'Yellows/Golds',
        'Gold/Black' => 'Yellows/Golds',
        'Gold/Brown' => 'Browns/Beiges',
        'Gold/Multi' => 'Yellows/Golds',
        'Gold/Red' => 'Yellows/Golds',
        'Granite' => 'Grays',
        'Graphite' => 'Grays',
        'Gray' => 'Grays',
        'Gray / Black' => 'Grays',
        'Gray / Multi' => 'Grays',
        'Gray / Silver' => 'Grays',
        'Gray / Teal' => 'Blues',
        'Gray / White' => 'Grays',
        'Gray Pond' => 'Grays',
        'Gray/Charcoal' => 'Blues',
        'Gray/Green' => 'Greens',
        'Green' => 'Greens',
        'Green / White' => 'Greens',
        'Gris' => 'Neutrals',
        'Gulf' => 'Multi',
        'Haze' => 'Multi',
        'Horizon' => 'Multi',
        'Hydrangea' => 'Blues',
        'Ice' => 'Blues',
        'Indigo' => 'Blues',
        'Indigo / White' => 'Blues',
        'Ivory' => 'Neutrals',
        'Ivory / Silver' => 'Neutrals',
        'Ivory/Brown' => 'Browns/Beiges',
        'Ivory/Chocolate' => 'Browns/Beiges',
        'Ivory/Dark Gray' => 'Multi',
        'Ivory/Gold' => 'Yellows/Golds',
        'Ivory/Gray' => 'Neutrals',
        'Ivory/Light Gold' => 'Yellows/Golds',
        'Ivory/Red' => 'Yellows/Golds',
        'Lemon' => 'Grays',
        'Light Blue' => 'Multi',
        'Light Blue/Brown' => 'Multi',
        'Light Brown' => 'Browns/Beiges',
        'Light Brown/Beige' => 'Browns/Beiges',
        'Light Gray' => 'Grays',
        'Light Green' => 'Greens',
        'Lilac / White' => 'Purples',
        'Lime' => 'Greens',
        'Loden' => 'Neutrals',
        'Lunar' => 'Multi',
        'Maize' => 'Yellows/Golds',
        'Mango' => 'Oranges/Rust',
        'Marine' => 'Blues',
        'Mariner' => 'Multi',
        'Meadow' => 'Blues',
        'Melon' => 'Reds',
        'Midnight' => 'Multi',
        'Midnight Blue' => 'Blues',
        'Mist' => 'Blues',
        'Moss' => 'Greens',
        'Multi' => 'Multi',
        'Mushroom' => 'Neutrals',
        'Mykonos' => 'Blues',
        'Mystic Blue' => 'Multi',
        'Natural / Ash' => 'Neutrals',
        'Natural / Bone' => 'Neutrals',
        'Natural / Cashmere' => 'Neutrals',
        'Natural / Charcoal' => 'Neutrals',
        'Natural / Ecru' => 'Neutrals',
        'Natural / Graphite' => 'Neutrals',
        'Natural / Gray' => 'Neutrals',
        'Natural / Linen' => 'Neutrals',
        'Natural / Slate' => 'Neutrals',
        'Natural/Ivory' => 'Neutrals',
        'Navy' => 'Blues',
        'Navy / White' => 'Blues',
        'Navy/Copper' => 'Multi',
        'Navy/Cream' => 'Browns/Beiges',
        'Navy/Green' => 'Blues',
        'Nectar' => 'Multi',
        'Noir' => 'Grays',
        'Oatmeal' => 'Neutrals',
        'Ocean' => 'Blues',
        'Ocean / Beige' => 'Multi',
        'Orange' => 'Oranges/Rust',
        'Orange / Blue' => 'Multi',
        'Orange / Multi' => 'Oranges/Rust',
        'Orange / White' => 'Oranges/Rust',
        'Ore' => 'Multi',
        'Pacific' => 'Blues',
        'Paprika / Aqua' => 'Multi',
        'Peacock' => 'Multi',
        'Pearl' => 'Neutrals',
        'Pewter' => 'Browns/Beiges',
        'Pewter / Charcoal' => 'Blues',
        'Pewter / Dark Gray' => 'Neutrals',
        'Pewter / Dark Green' => 'Neutrals',
        'Pewter / Gray' => 'Grays',
        'Pewter / Light Gray' => 'Neutrals',
        'Pewter / Light Silver' => 'Purples',
        'Pewter / Raspberry' => 'Purples',
        'Pewter / Sage' => 'Neutrals',
        'Pink/Green' => 'Multi',
        'Pistachio' => 'Blues',
        'Plum' => 'Purples',
        'Poinsetta' => 'Multi',
        'Polar' => 'Multi',
        'Pomegranate' => 'Reds',
        'Purple' => 'Purples',
        'Purple / White' => 'Purples',
        'Raisin' => 'Browns/Beiges',
        'Red' => 'Reds',
        'Red / White' => 'Reds',
        'Red/Black' => 'Reds',
        'Red/Brown' => 'Reds',
        'Red/Cream' => 'Reds',
        'Red/Light Gold' => 'Reds',
        'Red/Multi' => 'Oranges/Rust',
        'Red/Navy' => 'Reds',
        'Red/Teal' => 'Reds',
        'Royal' => 'Blues',
        'Rust' => 'Oranges/Rust',
        'Rust/Charcoal' => 'Oranges/Rust',
        'Sage' => 'Greens',
        'Sage/Ivory' => 'Browns/Beiges',
        'Sand' => 'Neutrals',
        'Sand / Light Gold' => 'Multi',
        'Sand / Terra Cotta' => 'Oranges/Rust',
        'Sea Glass' => 'Blues',
        'Sea Green/Green' => 'Blues',
        'Seal' => 'Grays',
        'Silver Sage' => 'Greens',
        'Slate' => 'Grays',
        'Slate / White' => 'Grays',
        'Smoke' => 'Grays',
        'Sorbet' => 'Multi',
        'Steel' => 'Multi',
        'Steel / Dark Gray' => 'Greens',
        'Steel / Light Silver' => 'Greens',
        'Stone' => 'Grays',
        'Storm' => 'Blues',
        'Straw' => 'Yellows/Golds',
        'Sumac' => 'Neutrals',
        'Sunset' => 'Oranges/Rust',
        'Tamarino' => 'Blues',
        'Tan / Blue' => 'Blues',
        'Tan / Charcoal' => 'Blues',
        'Tan / Cotton' => 'Browns/Beiges',
        'Tan / Light Green' => 'Greens',
        'Tan / Red' => 'Reds',
        'Tan / Rust' => 'Oranges/Rust',
        'Tan / Yellow' => 'Yellows/Golds',
        'Tan/Brown' => 'Browns/Beiges',
        'Tangerine' => 'Oranges/Rust',
        'Teal' => 'Blues',
        'Teal / Beige' => 'Multi',
        'Teal / Green' => 'Blues',
        'Teal/Navy' => 'Blues',
        'Thundercloud' => 'Blues',
        'Tobacco' => 'Neutrals',
        'Twilight' => 'Multi',
        'Violet' => 'Purples',
        'Yellow' => 'Yellows/Golds',
        'Yellow / White' => 'Yellows/Golds',
        'Zinfandel' => 'Neutrals',
        '' => 'Multi',
    );
    
    $row['rug_shape'] = array(
        'VALUE' => '{H}',
        "10' x 10' Round" => "Round",
        "10' x 13'-2\"" => "Rectangle",
        "2' x 3'" => "Rectangle",
        "2' x 3'-4\"" => "Rectangle",
        "2' x 8'" => "Hall/Stair Runner",
        "2'-1\" x 4'" => "Rectangle",
        "2'-10\" x 7'-10\"" => "Hall/Stair Runner",
        "2'-10\" x 8'" => "Hall/Stair Runner",
        "2'-2\" x 4'" => "Rectangle",
        "2'-3\" x 8'" => "Hall/Stair Runner",
        "2'-6\" x 6'" => "Rectangle",
        "2'-6\" x 8'" => "Hall/Stair Runner",
        "3'-2\" x 5'-4\"" => "Rectangle",
        "3'-6\" x 5'-6\"" => "Rectangle",
        "4' x 6'" => "Rectangle",
        "4'-9\" x 7'-6\"" => "Rectangle",
        "5' x 7'-6\"" => "Rectangle",
        "5' x 8'" => "Rectangle",
        "5'-3\" x 7'-6\"" => "Rectangle",
        "5'-6\" x 8'-6\"" => "Rectangle",
        "6' x 6' Round" => "Round",
        "7'-10\" x 11'" => "Rectangle",
        "7'-3\" x 9'-3\"" => "Rectangle",
        "7'-4\" x 10'-3\"" => "Rectangle",
        "7'-6\" x 10'-6\"" => "Rectangle",
        "7'-6\" x 10'-6\"" => "Rectangle",
        "7'-6\" x 7'-6\" Round" => "Round",
        "7'-6\" x 9'-6\"" => "Rectangle",
        "7'-9\" x 9'-9\"" => "Rectangle",
        "8' x 11'" => "Rectangle",
        "8' x 8' Round" => "Round",
        "8'-1\" x 11'-1\"" => "Rectangle",
        "8'-6\" x 11'-6\"" => "Rectangle",
        "9' x 9' Round" => "Round",
        "9'-1\" x 13'-2\"" => "Rectangle",
        "9'-2\" x 12'-2\"" => "Rectangle",
        "9'-3\" x 13'" => "Rectangle",
        "9'-6\" x 13'-6\"" => "Rectangle",
        "9'-8\" x 12'-7\"" => "Rectangle",
        "" => "Miscellaneous",
    );



    $row['rug_style'] = array(
        'VALUE' => '{C}',
        'Abbey' => 'Transitional',
        'Alexandra' => 'Traditional',
        'Amore' => 'Traditional',
        'Amzad' => 'Southwest/Lodge',
        'Arushi' => 'Solid',
        'Ashi' => 'Southwest/Lodge',
        'Aurora' => 'Shag',
        'Azeri' => 'Transitional',
        'Azeri Ii' => 'Transitional',
        'Azeri Iii' => 'Contemporary/Modern',
        'Azeri Iv' => 'Contemporary/Modern',
        'Barbary' => 'Southwest/Lodge',
        'Beckley' => 'Shag',
        'Bleecker' => 'Contemporary/Modern',
        'Brixton' => 'Contemporary/Modern',
        'Burke' => 'Solid',
        'Carina' => 'Transitional',
        'Cetara' => 'Geometric',
        'Channels' => 'Transitional',
        'Congo' => 'Animal Prints/Hides',
        'Contour' => 'Stripes',
        'Coronado' => 'Transitional',
        'Cosmo' => 'Transitional',
        'Daria' => 'Traditional',
        'Dim Sum' => 'Geometric',
        'Domus' => 'Shag',
        'Drake' => 'Traditional',
        'Fiona' => 'Transitional',
        'Goshen' => 'Southwest/Lodge',
        'Gramercy' => 'Geometric',
        'Gustavia' => 'Contemporary/Modern',
        'Harlow' => 'Transitional',
        'Hastings' => 'Indoor/Outdoor',
        'Indochine' => 'Shag',
        'Landon' => 'Solid',
        'Lorrain' => 'Transitional',
        'Lucka' => 'Transitional',
        'Luna' => 'Solid',
        'Magellan' => 'Traditional',
        'Mahsa' => 'Transitional',
        'Marlowe' => 'Solid',
        'Mojave' => 'Geometric',
        'Morisco' => 'Contemporary/Modern',
        'Moroccan Winds' => 'Shag',
        'Neela' => 'Transitional',
        'Pietra' => 'Southwest/Lodge',
        'Portico' => 'Geometric',
        'Qing' => 'Contemporary/Modern',
        'Raphia I' => 'Geometric',
        'Raphia Ii' => 'Geometric',
        'Rivington' => 'Transitional',
        'Rumi' => 'Geometric',
        'Sabrine' => 'Transitional',
        'Saphir' => 'Transitional',
        'Saphir Azar' => 'Transitional',
        'Saphir Cabo' => 'Transitional',
        'Saphir Callo' => 'Transitional',
        'Saphir Mah' => 'Transitional',
        'Saphir Obzeet' => 'Transitional',
        'Saphir Rubus' => 'Contemporary/Modern',
        'Saphir Yardley' => 'Transitional',
        'Saphir Zam' => 'Transitional',
        'Sargasso I' => 'Stripes',
        'Sattika' => 'Transitional',
        'Solis' => 'Indoor/Outdoor',
        'Soma' => 'Solid',
        'Sorel' => 'Contemporary/Modern',
        'Starnes' => 'Contemporary/Modern',
        'Tamar' => 'Transitional',
        'Tanner' => 'Transitional',
        'Thatcher' => 'Transitional',
        'Tortola' => 'Transitional',
        'Ustad' => 'Southwest/Lodge',
        'Verdigris' => 'Transitional',
        'Yale' => 'Traditional',
        'Ziba' => 'Traditional',
        '' => 'Transitional',
    );

    $row['rug_nav'] = array(
        'VALUE' => '{H}',
        "10' x 10' Round" => "Rounds 9+",
        "10' x 13'-2\"" => "10' x 14'",
        "2' x 3'" => "2' x 3'",
        "2' x 3'-4\"" => "2' x 3'",
        "2' x 8'" => "Runners 7'-8'",
        "2'-1\" x 4'" => "2' x 4'",
        "2'-10\" x 7'-10\"" => "Runners 6'-9'",
        "2'-10\" x 8'" => "Runners 8'-9'",
        "2'-2\" x 4'" => "2' x 4'",
        "2'-3\" x 8'" => "Runners 8'-9'",
        "2'-6\" x 6'" => "Runners 6'-9'",
        "2'-6\" x 8'" => "Runners 8'-9'",
        "3'-2\" x 5'-4\"" => "3'6\" x 5'6\"",
        "3'-6\" x 5'-6\"" => "3'6\" x 5'6\"",
        "4' x 6'" => "4' x 6' ",
        "4'-9\" x 7'-6\"" => "5'6\" x 7'6\"",
        "5' x 7'-6\"" => "5'6\" x 7'6\"",
        "5' x 8'" => "5' x 8'",
        "5'-3\" x 7'-6\"" => "5'6\" x 7'6\"",
        "5'-6\" x 8'-6\"" => "5' x 8'",
        "6' x 6' Round" => "Round 5'-6'",
        "7'-10\" x 11'" => "Miscellaneous",
        "7'-3\" x 9'-3\"" => "7' x 9'",
        "7'-4\" x 10'-3\"" => "7' x 10'",
        "7'-6\" x 10'-6\"" => "7' x 10'",
        "7'-6\" x 10'-6\"" => "7' x 10'",
        "7'-6\" x 7'-6\" Round" => "Round 7'-8'",
        "7'-6\" x 9'-6\"" => "7' x 9'",
        "7'-9\" x 9'-9\"" => "8' x 10'",
        "8' x 11'" => "8' x 11'",
        "8' x 8' Round" => "Round 7'-8'",
        "8'-1\" x 11'-1\"" => "8' x 11'",
        "8'-6\" x 11'-6\"" => "8' x 11'",
        "9' x 9' Round" => "Round 9+",
        "9'-1\" x 13'-2\"" => "9'6\" x 13'6\"",
        "9'-2\" x 12'-2\"" => "9' x 12'",
        "9'-3\" x 13'" => "9'6\" x 13'6\"",
        "9'-6\" x 13'-6\"" => "9'6\" x 13'6\"",
        "9'-8\" x 12'-7\"" => "9'6\" x 13'6\"",
        "" => "Miscellaneous",
    );


    $row['rug_size'] = array(
        'VALUE' => '{H}',
        "10' x 10' Round" => "10' x 10' Round",
        "10' x 13'-2\"" => "10' x 13'2\"",
        "2' x 3'" => "2' x 3'",
        "2' x 3'-4\"" => "2' x 3'4\"",
        "2' x 8'" => "2' x 8' Runner",
        "2'-1\" x 4'" => "2'1\" x 4'",
        "2'-10\" x 7'-10\"" => "2'10\" x 7'10\" Runner",
        "2'-10\" x 8'" => "2'10\" x 8' Runner",
        "2'-2\" x 4'" => "2'2\" x 4'",
        "2'-3\" x 8'" => "2'3\" x 8' Runner",
        "2'-6\" x 6'" => "2'6\" x 6' Runner",
        "2'-6\" x 8'" => "2'6\" x 8' Runner",
        "3'-2\" x 5'-4\"" => "3'2\" x 5'4\"",
        "3'-6\" x 5'-6\"" => "3'6\" x 5'6\"",
        "4' x 6'" => "4' x 6'",
        "4'-9\" x 7'-6\"" => "4'9\" x 7'6\"",
        "5' x 7'-6\"" => "5' x 7'6\"",
        "5' x 8'" => "5' x 8'",
        "5'-3\" x 7'-6\"" => "5'3\" x 7'6\"",
        "5'-6\" x 8'-6\"" => "5'6\" x 8'6\"",
        "6' x 6' Round" => "6' x 6' Round",
        "7'-10\" x 11'" => "7'10\" x 11'",
        "7'-3\" x 9'-3\"" => "7'3\" x 9'3\"",
        "7'-4\" x 10'-3\"" => "7'4\" x 10'3\"",
        "7'-6\" x 10'-6\"" => "7'6\" x 10'6\"",
        "7'-6\" x 10'-6\"" => "7'6\" x 10'6\"",
        "7'-6\" x 7'-6\" Round" => "7'6\" x 7'6\" Round",
        "7'-6\" x 9'-6\"" => "7'6\" x 9'6\"",
        "7'-9\" x 9'-9\"" => "7'9\" x 9'9\"",
        "8' x 11'" => "8' x 11'",
        "8' x 8' Round" => "8' x 8' Round",
        "8'-1\" x 11'-1\"" => "8'1\" x 11'1\"",
        "8'-6\" x 11'-6\"" => "8'6\" x 11'6\"",
        "9' x 9' Round" => "9' x 9' Round",
        "9'-1\" x 13'-2\"" => "9'1\" x 13'2\"",
        "9'-2\" x 12'-2\"" => "9'2\" x 12'2\"",
        "9'-3\" x 13'" => "9'3\" x 13'",
        "9'-6\" x 13'-6\"" => "9'6\" x 13'6\"",
        "9'-8\" x 12'-7\"" => "9'8\" x 12'7\"",
        "" => "",
     );

    $row['rug_material'] = '{T}';
    $row['mfg_collection'] = '{C}';
    $row['assembly_req'] = '';
    $row['country_of_manufacture'] = '';
    $row['ship_type'] = 'Drop Ship';
    $row['lead_time'] = '14 Days';
    $row['enable_googlecheckout'] = 'Yes';
    $row['gift_message_available'] = 'No';
    $row['has_options'] = '0';
    $row['custom_layout_update'] = '';
    $row['page_layout'] = '1 column';
    $row['options_container'] = 'container1';
    $row['custom_design'] = '';
    $row['custom_design_from'] = '';
    $row['custom_design_to'] = '';
    $row['news_from_date'] = '';
    $row['news_to_date'] = '';
    $row['reward_no_discount'] = '';
    $row['reward_points'] = '';
    $row['product_name'] = '';
    $row['product_type_id'] = 'simple';
    $row['product_status_changed'] = '';
    $row['product_changed_websites'] = '';
    $row['recurring_profile'] = '';
    $row['shipping_height'] = '{S}';
    $row['shipping_width'] = '{R}';
    $row['shipping_length'] = '{Q}';
    $row['pile_height'] = '';
    $row['construction'] = '{M}';
    $row['stain_resistant'] = '';
    $row['fire_resistant'] = '';
    $row['care_cleaning'] = '';
    $row['warranty'] = '';

    